### ISSUE TITLE
Conditional registration predicates are not properly checked during verification

### ISSUE THREAD

**Issue by onyxmaster** [simpleinjector/SimpleInjector#276]
Consider the following code:

```c#
// Types
interface IA { }
interface IB { }
class A : IA { public A(IB b) { } }

// Registrations
var container = new Container();
container.RegisterConditional<IA, A>(_ =>
{
	Console.WriteLine("Predicate checked.");
	return false;
});
Console.WriteLine("Verifying.");
container.Verify();
```

This disallows advanced scenarios with optional dependency registration.

**Comment by dotnetjunkie** [comment]
This behavior is by design. Simple Injector verifies whether the registered type `A` can be constructed and will run it through diagnostics, but its predicate is only called if the conditional type itself is a dependency of some other registration. This behavior enables users to write simpler registration code.

In case a conditional registration is requested as root type (instead of being a dependency of another type), the `Consumer` property of the `PredicateContext` class (that Simple Injector supplies when calling the predicate) will be `null`. Since users would typically only use conditional registrations on types that are solely used as dependencies (so not as types that are resolved directly, as in: `GetInstance<IA>()`), they will typically assume the `Consumer` property is set, and will not check for `null`. If Simple Injector would call the predicate during verification when the type itself isn't depended upon, it would be forced to supply `null` to the `Consumer` property (since in that case there is no sensible value to set). This would break users' expectation, who would be forced to add proper `null` checks (and by doing so complicate their code), just because Simple Injector calls their predicate differently during verification.

On the other hand, letting Simple Injector inject some default value into `Consumer` of root types, could complicate things as well, because in case the user doesn't want the type to ever be resolved as root type, he will have to explicitly add an extra check (and throw an exception) instead of letting the code blow with a `NullReferenceException`.

Typically it is fine that Simple Injector doesn't call your predicate this way, since once you start letting the conditional registration be a dependency (which is the only sensible use case for conditional registrations, since conditional registrations are not meant to change based on runtime conditions), the predicate gets called and therefore gets verified.

I hope this makes sense.

**Comment by onyxmaster** [comment]
Thank you for the detailed reply, Steven.

While I agree with the logic behind the explanation, I'm still not sure how I should handle optional dependencies. In our application, the conditional's predicate is testing for an existing registration of another, optional dependency. This is done in a separate package to reduce composition root boilerplate code:
```c#
container.RegisterConditional<ISomeProvider, Implementation.SomeProvider>(Lifestyle.Singleton, 
    context => container.GetRegistration(typeof(ISomeProviderImplementationDependency)) != null);
```
The `Implementation.SomeProvider` has a constructor-injected dependency of `ISomeProviderImplementationDependency`, so I would like to container to provide the `ISomeProvider` only if its dependency (a data source in an actual application) is registered in the application composition root.

The `ISomeProvider` is the used as an optional constructor-injected dependency to another service:
```c#
public ServiceImplementation(Optional<ISomeProvider> someProvider)
{
    ...
}
```

The optional types are injected by handling the `Container.ResolveUnregisteredType` handler that automatically creates registrations for `Optional<T>`, by resolving the `T` from the container (I can post the code, but I believe it's not really needed here).

I very much like the idea of optional dependencies and non-self-contained registrations, since it gives us a lot of flexibility in composing different modules. The method described above works great for us, but I would like to have verification too. Am I doing something wrong here? I understand that separate non-self-contained packages smell of composition root smearing, but they are convenient enough to warrant their use (also they are discoverable and composable by themselves, since we have some package filtering in place). I understand that I can move the code out of the package into the composition root itself, but in this case it looks like unnecessary copy-paste, this is "framework" code from the application perspective, which also leads to leaking implementation details of how the module that contains the package is built from the inside. I've also considered the option of null object pattern instead of optional dependencies, but the requirement to register this object looks... imperfect.

Maybe you've got any advice on this?

**Comment by dotnetjunkie** [comment]
It's hard to say whether you're doing something wrong, but I must admit this is the first time I saw anyone make a conditional registration like this.

In general I would advise against using optional types and injection of types like your own `Optional<T>`, or `Lazy<T>` (and to some extend `IEnumerable<T>` as well). They complicate the consumer's code and cause sweeping changes throughout the code base when a type becomes optional or requires heavy initialization later on.

You are already mentioning the [Null Object Pattern](https://en.wikipedia.org/wiki/Null_Object_pattern), and this is general a much better way to make the consumer oblivious of the fact that a dependency might be missing. In other words, in case when no real implementation (of `ISomeProvider` in your case) is prevent, you register an implementation that has no observable behavior (it is empty or 'null'). This prevents you from having to change all classes that take a dependency on `ISomeProvider` and also prevents problems where some consumer accidentally depends on `ISomeProvider` directly, and it fill also force the real `ISomeProvider` registration (if present) to be more easily verified by the container.

In your case you probably even don't have to create a Null Object implementation for `ISomeProvider`, since it is only the `ISomeProviderImplementationDependency` that seems truly optional. So the `ISomeProvider` can become a simple unconditional registration, while it internally uses the `ISomeProviderImplementationDependency` dependency, while it has no clue whether or not this is a real implementation or a Null Object implementation (and it shouldn't care).

I have no idea why you think the use of the Null Object pattern "looks... imperfect". It might be that your abstractions are violating the [Interface Segregation Principle](https://en.wikipedia.org/wiki/Interface_segregation_principle), because that would make it awkward to create Null Object implementations for them.

Can you elaborate on why you think the use of the pattern looks imperfect to you?

**Comment by onyxmaster** [comment]
I don't think I violate ISP, because all these interfaces in question have no more than 1 member =)

The `ISomeProviderImplementationDependency` is a data source. I believe I can change it to return an `Optional<Data>` and add a null object implementation to return `None`, but then I'll have to register this null object when I don't want to use any data source. While this is acceptable, this is what I meant when I said it's imperfect -- I was only speaking of the requirement to register a null object implementation when I could just not register anything. I understand the merits of "explicit over implicit", but in this case it looks more like "too much typing for the functionality you don't use just to get it running".

**Comment by dotnetjunkie** [comment]
> I don't think I violate ISP, because all these interfaces in question have no more than 1 member =)

Agreed. It's unlikely that you violate ISP when the interface has just one member :)

I think returning `Optional<Data>` would be better than injecting an `Optional<T>` as dependency, but I agree this isn't a very attractive solution as well, because this as well means that you would have to change the interface and all its implementations in case the implementation might be missing. In general this would work in case the Null Object implementation can return a valid (but empty) `Data` instance. If this is not possible, the solution is indeed to move the problem up one level; which will again result in a Null Object implementation for `ISomeProvider`.

I still believe that you don't have to inject `Optional<T>` dependencies; I think you should prevent doing this by all means. In that case I would still prefer keeping the registration for `ISomeProvider` and `ISomeProviderImplementationDependency` together, because that would remove the need from having to query for `ISomeProviderImplementationDependency` inside the `ISomeProvider` conditional predicate.

But if that isn't an option, calling `GetService` inside the predicate is still a better option than polution your code base with `Optional<T>` dependencies.

**Comment by onyxmaster** [comment]
Thank you, Steven. The only question that I have remaining is why do you consider optional dependencies so polluting? Am I missing some crucial background information here?

**Comment by dotnetjunkie** [comment]
> The only question that I have remaining is why do you consider optional dependencies so polluting? Am I missing some crucial background information here?

Earlier in this thread I made the resemblance between your `Optional<T>` and things like `Lazy<T>` and `IEnumerable<T>`. When wrapping your dependency in one of those types you are leaking implementation details to the consumer:

 - With `Optional<T>` you are leaking details about whether or not an implementation is available.
 - With `Lazy<T>` you are leaking details about the implementation being heavy or expensive to create.
 - With `IEnumerable<T>` you are leaking details about there being multiple implementations available.
 
All these things are implementation details and by doing so you are effectively violating the Dependency Inversion Principle that states that you should depend on abstractions, not implementations.

The problem with this is that you never know what dependency might become optional later on, but when this happens, you will have to through the code base and make sweeping changes. Any time you have to make sweeping changes throughout your code base you are effectively violating the Open/Closed Principle that dictates that it must be possible to make changes without making sweeping changes.

Besides this, making dependencies optional increases the complexity of the consumers that require those dependencies. This might not be that obvious at first, but you will notice this during testing, since you will have to test both the default case and the none-case.

Of course you can prevent having to make these sweeping changes by making everything optional up front, but that would obviously lead to extreme code polluting. This supports the previous argument about increased complexity: when making everything optional up front pollutes the code base and increases complexity, it has to do the same when we only do it part of the time. The amount of increases complexity will be less, but still present.

Do note that this doesn't mean that you can't inject any `Optional<T>`, `Lazy<T>` or `IEnumerable<T>` *anywhere*. You should limit this to the composition root. The composition root can contain proxy implementations that accept an `Optional<T>`, `Lazy<T>` or `IEnumerable<T>` for the `T` that they also implement. The proxy implementation for `IEnumerable<T>` even has a special pattern name: Composite.

``` C#
class OptionalSomeProviderProxy : ISomeProvider
{
	Optional<ISomeProvider> optional;
	public OptionalSomeProviderProxy(Optional<ISomeProvider> optional) {
		this.optional = optional;
	}
	
	public void SomeMethod() => if (optional.HasValue) optional.Value.SomeMethod();
}
```

Implementing such proxy class would consist of more code than having one single consumer in your code base that requires this optional dependency. This is mainly because of syntactical limitations of our C# language. I believe this will improve in C# 7, but that's not the point here. The importance is not letting implementation details leak into the consumers. Because if you do this with optional, what happens when the implementation (when presented) is heavy to initialize? You will (again) have to change the consumer and let it depend on `Optional<Lazy<T>>` instead. That sure aint pretty.

I hope this makes sense.

**Comment by onyxmaster** [comment]
Great response, Steven! Thank you again.

**Comment by ensisnoctis** [comment]
I still have an inquiry towards the `IEnumerable<T>` part. Consider this code:

	public class Service<T>
	{
		protected IEnumerable<T> Data;
		public Service(IEnumerable<T> data) => this.Data = data;
		public virtual IEnumerable<T> GetData => this.Data;
	}
	
	public class NumberService : Service<float>
	{
		public NumberService(IEnumerable<float> data) : base(data) { } // A
	}
	
	public class StringService : Service<string>
	{
		public StringService(IEnumerable<string> data) : base(data) { } // A
	}
	
	
	
	void Main()
	{
		var ioc = new Container();
		ioc.RegisterCollection(typeof(Service<>), new[] { this.GetType().Assembly });
		ioc.RegisterConditional(typeof(IEnumerable<float>),  Lifestyle.Singleton.CreateRegistration(() => new[] { 1.41f, 2.71f, 3.14f }, ioc), context => true);   // A
		ioc.RegisterConditional(typeof(IEnumerable<string>), Lifestyle.Singleton.CreateRegistration(() => new[] { "sqrt2", "e", "pi"  }, ioc), context => false);  // A, C
	
		ioc.GetInstance(typeof(Service<float>)).Dump();
		ioc.GetInstance(typeof(Service<string>)).Dump();
	}

You can see a base `Service` and its two implementations, both of which take literal constructor parameters. Those are supplied in `Main()`, conditionally.

Despite conditional prohibiting it (comment `C`), the second service gets resolved successfully. I did read this topic and understand that it's by design, I even got it to work by replacing all `IEnumerable<T>` with `T[]` array type (everywhere commented `A`).

My question though is this: because `IEnumerable<T>` is violating some principles here and there, why not just throw an exception explaining it instead of doing such an, in my humble opinion, unintuitive thing as to override the predicate (`C`) silently?

**Comment by dotnetjunkie** [comment]
Hi @ensisnoctis,

I'm afraid you misunderstand the discussion in this issue here. The designed behavior of Simple Injector is to prevent calling the predicate in case `Verify` is called.

When it comes to resolving types using `GetInstance`, the predicates _are_ called.

What you are experiencing however is an unfortunate bug that seems to appear only when explicitly registering an `IEnumerable<T>`. I'm therefore moving your response to a new thread.
