### ISSUE TITLE
Add [assembly: AllowPartiallyTrustedCallers()] to Simple Injector 4

### ISSUE THREAD

**Issue by fatalerrorx** [simpleinjector/SimpleInjector#408]
I use simple injector in an ASP application and after the upgrade from 3 to 4 am getting security exceptions.

**Comment by dotnetjunkie** [comment]
I just pushed [v4.0.2](https://www.nuget.org/packages/SimpleInjector/4.0.2) to NuGet that fixes this problem.

**Comment by dotnetjunkie** [comment]
Hi @fatalerrorx, 

I'm considering removing the `AllowPartiallyTrustedCallers` attribute again in v4.0.3, since the addition of this attribute [completely broke Simple Injector](https://github.com/simpleinjector/SimpleInjector/issues/410#issuecomment-295321503).

Can you give more details about this problem and how to reproduce it. I need more information about this.

**Comment by steelerc** [comment]
Not sure if its the same thing, but after upgrading to 4.0.2 with an aspcore project I'm getting TypeLoadException: Inheritance security rules violated while overriding member: &#x27;SimpleInjector.Integration.AspNetCore.Mvc.SimpleInjectorControllerActivator.Create(Microsoft.AspNetCore.Mvc.ControllerContext)&#x27;. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

**Comment by dotnetjunkie** [comment]
@steelerc, yep, that's the same thing. I reverted that change in v4.0.3. Should work again.

**Comment by steelerc** [comment]
I'm still getting the same errors with 4.0.3.  Just as a simple test I took your code from the docs exactly in the Startup.cs minus the lines around custom middleware and still get the same issue.   IF I comment out the two lines around AddSingleton<IControllerActivator>... then I can step into the methods while debugging.  Otherwise the security exception is thrown and I never see Configure, ConfigureServices or InitializeContainer even being called.  

Reproduction steps: 
1) Create a new C#->Web->ASP.Net Core Web Application (.NET Core) project.  
2) Copy your code from the documentation @ http://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html  
3) Edit the csproj file, change TargetFramework from netcore10 to net462.  
4) Run the app, the error ensues.

**Comment by dotnetjunkie** [comment]
I just tested this myself with v4.0.3 and it should actually work. Make sure you cleared your build and make sure everything is usinng v4.0.3 (not only SimpleInjector.Integration.WebApi, but also SimpleInjector.dll v4.0.3).

**Comment by steelerc** [comment]
Ok so to clarify for my problem I am using SimpleInjector 4.0.3 and SimpleInjector.Integration.AspNetCore.Mvc 4.0.3  (NOT SimpleInjector.Integration.WebApi).  Not sure if this matters or not.   Thanks for the help in getting this resolved.

**Comment by steelerc** [comment]
Maybe I need to move my thread to a new issue?

**Comment by steelerc** [comment]
Smallest simplest project showing my error.  Run it from VS2017 default IISExpress, browser opens, spins, stops.  hit refresh, error shows.
[WebApplication1.zip](https://github.com/simpleinjector/SimpleInjector/files/937791/WebApplication1.zip)

**Comment by dotnetjunkie** [comment]
Ouch, that's painful. Both SimpleInjector.Integration.AspNetCore and SimpleInjector.Integration.AspNetCore.Mvc still contain that `AllowPartiallyTrustedCallers` attribute :(

I pushed version v4.0.4 of both the SimpleInjector.Integration.AspNetCore and SimpleInjector.Integration.AspNetCore.Mvc to NuGet. Now everything should work again.

**Comment by tiesont** [comment]
@dotnetjunkie Getting the same System.TypeAccessException exception in a non-core ASP.NET MVC project - safe to assume it's the same issue?

**Comment by steelerc** [comment]
@dotnetjunkie  Thanks Steven.  This has resolved all of my issues that I can immediately test and check.  Awesome quick turn around on the issue.

**Comment by fatalerrorx** [comment]
I have implemented a work around on my end. In version 3 it just worked.

**Comment by dotnetjunkie** [comment]
@fatalerrorx, please help us improving Simple Injector. Can you provide us with more information about your case?

Can you describe your situation and how that lead to the error. Perhaps you can provide us with a minimum reproducible example?

Can you explain what you did to work around the issue?

**Comment by fatalerrorx** [comment]
My web app runs in partial trust so all referenced assemblies must be AllowPartiallyTrustedCallers. Since simple injector is no longer marked AllowPartiallyTrustedCallers I simply marked all method calls to simple injector with SecuritySafeCritical

**Comment by dotnetjunkie** [comment]
Although we do like to support running in partially trusted environments, please note that Microsoft does _not_ support partial trust and medium trust anymore when running in an ASP.NET application.

For more information, please see the following articles:

 - [ASP.NET Partial Trust does not guarantee application isolation](https://support.microsoft.com/en-us/help/2698981/asp.net-partial-trust-does-not-guarantee-application-isolation)
 - [What not to do in ASP.NET: Medium trust](https://docs.microsoft.com/en-us/aspnet/aspnet/overview/web-development-best-practices/what-not-to-do-in-aspnet-and-what-to-do-instead#medium)

**Comment by Sebazzz** [comment]
I'm having this issue when calling API from the `Packaging` NuGet package. Could you push a new version of that one as well?

    Attempt by security transparent method 'SimpleInjector.PackageExtensions.RegisterPackages(SimpleInjector.Container, System.Collections.Generic.IEnumerable`1<System.Reflection.Assembly>)' to access security critical type 'SimpleInjector.Container' failed.

**Comment by dotnetjunkie** [comment]
Good point. Will do

**Comment by dotnetjunkie** [comment]
@Sebazzz, please try out [SimpleInjector.Packaging 4.0.4](https://www.nuget.org/packages/SimpleInjector.Packaging/4.0.4).

**Comment by dotnetjunkie** [comment]
Fixed with [Simple Injector v4.0.6](https://www.nuget.org/packages/SimpleInjector/4.0.6).
